### ISSUE TITLE
node-red-ui-node-table auto size not working and zero data hides table

### ISSUE THREAD

**Issue by peterprib** [node-red/node-red-ui-nodes#10]
### What are the steps to reproduce?
add table to dash board both on auto size and specify columns.  Send one some data and the other a empty list

### What happens?
![image](https://user-images.githubusercontent.com/7586884/63323410-11418600-c369-11e9-8fd5-fac8a66ca9cc.png)

### What do you expect to happen?
On table visible at least a few lines shown
Expect other table to be visible with only specified columns 
Override to manual will show lines on visible table

### Please tell us about your environment:
19 Aug 21:42:27 - [info] Node-RED version: v0.20.7
19 Aug 21:42:27 - [info] Node.js version: v11.6.0
19 Aug 21:42:27 - [info] Windows_NT 10.0.14393 ia32 LE
- [ ] Node-RED version:
- [ ] node.js version:
- [ ] npm version:
- [ ] Platform/OS:
- [ ] Browser:

**Comment by peterprib** [comment]
Just noticed caused when % is used in width on visible table

**Comment by dceejay** [comment]
Pushed version 0.1.0 that adds some better height defaults.

**Comment by peterprib** [comment]
Thanks has fixed.

p.s. as an improvement a column type that if selected sends a message of row content.  Even better still if had pull down list of actions and that sent in message

**Comment by dceejay** [comment]
Version 0.1.0 already has the ability to send the row data - or did you mean something else ?

**Comment by peterprib** [comment]
My apologies hadn't realized ticking send data makes a port appear.  suppose should have read info better.  Suggest improvement of action list appearing and selected actions sent as an attribute along with selected attribute
Was thinking this could be done by a special columns.  Could then be more dynamic by  payload having pivot information making it changeable based on column.   For example if row reflected off state then a choice on only on state is shown and visa versus.  This would also allow multiple types of pull down list so one could change various states based on column they represent, e.g start/stop, rate slow/fast etc which may be changeable variations to the artifact represented by the row.
