### ISSUE TITLE
Tables do not show on Dashboard when ui: path is set to ""

### ISSUE THREAD

**Issue by HansenNO** [node-red/node-red-ui-nodes#14]
### Which node are you reporting an issue on?
node-red-node-ui-table
### What are the steps to reproduce?
set:
**_httpAdminRoot: '/admin'_**
**_ui: { path: "" }_**
in settings.js

### What happens?
Tables does not show up in dashboard when above settings are applied.

### What do you expect to happen?
Table to show with above settings

### Please tell us about your environment:
- [ ] Node-RED version: 0.20.8
- [ ] node.js version: 10.16.3
- [ ] npm version: 6.9.0
- [ ] Platform/OS: Ubuntu 19.10 server.
- [ ] Browser: Firefox 69 (64 bit)

**Comment by knolleary** [comment]
Whilst we should probably handle this, it would be more usual to set the ui path to `/` if you want it served from the root.

**Comment by HansenNO** [comment]
That was a quick response :)

Just tried it, i.e I set:
**_ui: { path: "/" }_** instead of **_ui: { path: "" }_**
It produce the same issue.

However:
**_ui: { path: "test" }_**
works OK.
