### ISSUE TITLE
Install fails via palette manager

### ISSUE THREAD

**Issue by ASH3xC0d3** [node-red/node-red-ui-nodes#15]
### Which node are you reporting an issue on?
node-red-node-ui-table 0.1.4
### What are the steps to reproduce?
Install via manage palette returns Syntax Error in cmd window
Error displayed: 
[info]  - node-red-node-ui-table : SyntaxError: Invalid regular expression: 
       /^\ui\ui-table\<.*>\/?$/: Unmatched '>' <line:130>
### What happens?
Fails to install table node
### What do you expect to happen?
:-) to install this node
### Please tell us about your environment:

- [ ] Node-RED version:20.6
- [ ] node.js version:10.16.0
- [ ] npm version:
- [ ] Platform/OS:Windows 7
- [ ] Browser:Chrome

**Comment by dceejay** [comment]
pushed fix in version 0.1.5
