### ISSUE TITLE
Table node sizing does not appear to work

### ISSUE THREAD

**Issue by mkarliner** [node-red/node-red-ui-nodes#17]
### Which node are you reporting an issue on?
table node

### What are the steps to reproduce?
Import the code from the simple table 
example at
https://github.com/node-red/node-red-ui-nodes/blob/master/node-red-node-ui-table/examples/1%20Simple%20table.json

### What happens?
The table only renders the first two rows of data

### What do you expect to happen?
All the rows should be rendered.

### Please tell us about your environment:

- [ ] Node-RED version: 1.0
- [ ] node.js version: 10.16.3
- [ ] npm version: 6.11.2
- [ ] Platform/OS: Raspbian 9.11
- [ ] Browser: Chrome
![Node-RED_Dashboard](https://user-images.githubusercontent.com/1651042/65899361-78f8e100-e3ab-11e9-8ac2-d11c36629f3a.png)

I've tried various setting of 'size' including auto with no success.

**Comment by dceejay** [comment]
There are only two rows of data in that example.
Please use the discourse forum for general How-To questions.

**Comment by mkarliner** [comment]
Sorry, I should have said I've copy / pasted it up to five rows with the same result.
Overall, sizing seems to be fairly broken (or I don't understand it, which is quite possible).
With my own data, for instance, setting the number of row disables the scroll bar even when
there are more rows than specified.

**Comment by dceejay** [comment]
The size should be set by the widget size option.... but... the size of the widget is set by the units defined in the dashboard site tab which defaults to 48 pixels - whereas each row is probably about 30 pixels so it's not a 1:1 relationship. 
You should also be able to set it to auto - but in that case it won't resize until after you have loaded the data nad then refreshed the page... so not so useful.

**Comment by mkarliner** [comment]
Thanks for all of that. I realized that the default tab layout will cause odd sizing issues with
table unless it is changed to accomodate the table size. I assumed that it would allow the
table as much width as it needed.
