### ISSUE TITLE
table link formatting

### ISSUE THREAD

**Issue by dsl400** [node-red/node-red-ui-nodes#22]
### Which node are you reporting an issue on?
node-red-node-ui-table

### Please tell us about your environment:
https://github.com/node-red/node-red-ui-nodes/blob/master/node-red-node-ui-table/examples/2%20Richer%20table.json
in the example for the Link I found:  
```
"formatterParams": {
    "target": "_blank"
 }
```
however I cannot find a way to set the text label for a link and maybe place a small button with an icon

**Comment by Christian-Me** [comment]
Hi,
your problem should now be solvable. Take a look on the latest update:
https://flows.nodered.org/node/node-red-node-ui-table
This gives you nearly all possibilities the underlying [Tabulator](http://tabulator.info/)  library provides.
