### ISSUE TITLE
node-red-node-ui-table: Cannot GET /endpoint/ui/ui-table/js/tabulator.js (404)

### ISSUE THREAD

**Issue by bjobo** [node-red/node-red-ui-nodes#27]
### Which node are you reporting an issue on?
node-red-node-ui-table

### What are the steps to reproduce?
- Install HASSIO (https://www.home-assistant.io/hassio/)
- Install node-red plugin
- Install node-red dashboard and node-red-node-ui-table via 'Palette'
- Add node-red-node-ui-table to flow and dashboard and deploy
- Open Dashboard with table node

### What happens?
Dashboard ist loading, but table is not shown. The Browser log shows an error.

Browser
```
https://HOSTNAME:1880/endpoint/ui/ui-table/css/tabulator.min.css
Cannot GET /endpoint/ui/ui-table/css/tabulator.min.css
404 GET https://HOSTNAME:1880/endpoint/ui/ui-table/js/tabulator.js
Cannot GET /endpoint/ui/ui-table/js/tabulator.js
```
node-red log file:
```
[17/Feb/2020:20:02:22 +0100] 404 -(192.168.179.22) GET /endpoint/ui/ui-table/css/tabulator.min.css HTTP/2.0 (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0)
[17/Feb/2020:19:58:43 +0100] 404 -(192.168.179.22) GET /endpoint/ui/ui-table/js/tabulator.js HTTP/2.0 (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0)
```
### What do you expect to happen?
Show the table

### Please tell us about your environment:
- [x] Node-RED version: v1.0.3
- [x] Node.js  version: v12.14.0
- [x] npm version: npm@6.13.4
- [x] Platform/OS: Linux 4.19.97-v7+ arm LE
- [x] Browser: Firefox / Chrome

### Solution:
I was able to resolve the problem by changing the following lines in node_modules/node-red-node-ui-table/node.js:
```
// Original: Not working
// var fullPath = path.join(RED.settings.httpNodeRoot, uipath, '/ui-table/*').replace(/\\/g, '/');;

// Fix: Had to remove RED.settings.httpNodeRoot from path and add a leading slash
// Note: httpNodeRoot is also not used in node-red-dashboard!
var fullPath = path.join('/', uipath, '/ui-table/*').replace(/\\/g, '/');
```
Note: RED.settings.httpNodeRoot does resolves to `/endpoint/`

**Comment by dceejay** [comment]
Many thanks for the issue and fix

**Comment by jpeg2600** [comment]
@dceejay  FYI the commited fix only works if the ui is at the default ui path. In my case, I changed my Node-Red config to have the ui at the root and the admin panel at /admin and that broke the module. 

Thanks to this thread I was able to fix it with ease. I just changed the uipath variable in node.js: 

`var uipath = '';`
