### ISSUE TITLE
node-red-node-ui-table does not render when Name field has a single quote in it

### ISSUE THREAD

**Issue by MichaelLeeHobbs** [node-red/node-red-ui-nodes#28]
### Which node are you reporting an issue on? 
node-red-node-ui-table

### What are the steps to reproduce? 
Add a table node with a name containing a single quote, for example, "Site ID's"

### What happens? 
The table does not render. Base on an inspection of html it seems to be completely missing.

### What do you expect to happen? 
The table to render or for a note/warning that single quotes are not supported.

### Please tell us about your environment:

- [x] Node-RED version: Docker: nodered/node-red:latest image id: ddb23b78261e
- [x] node.js version: Docker: nodered/node-red:latest image id: ddb23b78261e
- [x] npm version: Docker: nodered/node-red:latest image id: ddb23b78261e
- [x] Platform/OS: DockerDesktop for Windows for Dev and Centos 7 for deployment
- [x] Browser: Latest Chrome

**Comment by Christian-Me** [comment]
Using setup via ui_control works
![image](https://user-images.githubusercontent.com/15779507/75482996-29dcc980-59a6-11ea-9c4e-2e9af80bcce5.png)
As I already have some console.log`s in place I thought I could solve a issue but ,,,

without a single quote in "sidebar config" it looks like this
![image](https://user-images.githubusercontent.com/15779507/75483673-a2905580-59a7-11ea-97e9-650e94f64b06.png)
but with a single quote as title there is no init happening
![image](https://user-images.githubusercontent.com/15779507/75483769-c94e8c00-59a7-11ea-8e9a-4a3242e0ae73.png)
So I assume that the dashboard having problems with the single quote. Workaround?
![image](https://user-images.githubusercontent.com/15779507/75484186-8fca5080-59a8-11ea-8897-b386b8e10ca7.png)
sorry can`t help here either

**Comment by dceejay** [comment]
Temporary workaround is to use  `&#39;`  instead
