### ISSUE TITLE
Table disappears on click with Send data on click checked, but only on first click.

### ISSUE THREAD

**Issue by MichaelLeeHobbs** [node-red/node-red-ui-nodes#29]
### Which node are you reporting an issue on?
node-red-node-ui-table

### What are the steps to reproduce?
Create a simple table with injected columns or import example ui_control table.

### What happens?
After clicking on a row with the "Send data on click" checked the table will disappear. It is, however, more complex than that. If you re-inject the data the table will reappear and becomes stable. Thus this issue only seems to occur on the first click and only when "Send data on click" is checked.

### What do you expect to happen? 
The table to not disappear. 😄 

### Please tell us about your environment:

- [x] Node-RED version: Docker: nodered/node-red:latest image id: ddb23b78261e
- [x] node.js version: Docker: nodered/node-red:latest image id: ddb23b78261e
- [x] npm version: Docker: nodered/node-red:latest image id: ddb23b78261e
- [x] Platform/OS: DockerDesktop for Windows for Dev and Centos 7 for deployment
- [x] Browser: Latest Chrome

**Comment by MichaelLeeHobbs** [comment]
If you use a timestamp inject with a time of 0.1 seconds or a ui control update then the above issue occurs. If you increase the timestamp inject to 5 seconds then the table is stable. I've got a workaround where I do an initial inject at 1 second and a second one with a 5-second delay.

**Comment by Christian-Me** [comment]
Hi,
a workaround is fine for now....
I can reproduce this issue not exactly as you described on dashboard 2.19.4

1. press inject and the table appear
2. switch tabs and come back or press reload (browser) the table reappears
3. click on a cell and a message arrives at the debug note. The table stays. (can be repeated)
4. reload or switch tabs after one or many clicks were made **table is empty** no data no configuration.

on 2.19.3 point 4 is different:
3. click on a cell and a message arrives at the debug note. The table content disappear. 
3. but after 2 injects as described in the issue the table stays
4. always empty after reload

This happens not only with the ui_control example but with the richer table too.

I placed two console logs: one where messages arrive
```
$scope.$watch('msg', function (msg) {
   console.log("ui-table message arrived:",msg,$scope.tabledata);
```
and one in the callback
```
opts.cellClick = function(e, cell) {
  console.log("cellClick",$scope.tabledata);
  $scope.send({topic:cell.getField(), payload:cell.getData(), row:(cell.getRow()).getPosition()});
};
 
```
after comlete restart:
![image](https://user-images.githubusercontent.com/15779507/75479613-1dee0900-59a0-11ea-8256-bdc1a99eb49a.png)
after inject
![image](https://user-images.githubusercontent.com/15779507/75479751-568de280-59a0-11ea-840a-e3ff28373b9a.png)
after browser reload- the "last" table message is replayed and restores the table
![image](https://user-images.githubusercontent.com/15779507/75479824-7ae9bf00-59a0-11ea-8c8e-7bf8447d24e7.png)
after click on one cell the message is emitted
![image](https://user-images.githubusercontent.com/15779507/75479934-a79dd680-59a0-11ea-9145-e557580e3f82.png)
but then after browser reload - the "last" table message is replayed, not the message which sets up the table
![image](https://user-images.githubusercontent.com/15779507/75480314-580bda80-59a1-11ea-814e-05525d021ef9.png)

So I suspect that the outgoing messages are somehow cached (like incoming) messages.
Sorry I could not solve this but perhaps this could help someone who is more into the core functions of the dashboard

**Comment by MichaelLeeHobbs** [comment]
I've given up on node-red-node-ui-table and gone with node-red-node-ui-etable. node-red-node-ui-table has additionally issue I haven't reported yet and is effectively not useable in the Docker NodeRed latest. While the documentation is weak on node-red-node-ui-etable it, however works well.

**Comment by dceejay** [comment]
well a heads up on the additional issue would be appreciated so we could fix it.
(as we have with the one above)

**Comment by Christian-Me** [comment]
I think there is still an issue here and I like to help. See https://github.com/node-red/node-red-ui-nodes/issues/29#issuecomment-592148644

But my knowledge of the dashboard mechanics starts here: 
`$scope.$watch('msg', function (msg) { ... }`
The problem as described after a message is sent to Node-RED because since sometimes not the message filling the table is replayed but the last message out then it is time to redraw the table.
Perhaps ui-table does something wrong when it sends the cellClick message with `$scope.send()`.

Perhaps somebody can give me a hint what the dashboard expects or some kind of "theory of operations"

The ui-table command PR does not solve this. It can be used as a workaround but it is more for experienced users, not users simply want to display a table

I think the solution lies in the dashboard not sending messages back which originates from the ui-node itself and not storing this for replay. I could do a workaround simply storing the table after sending it to ui-table but this results in a double data set on the client and difficulties to clear the table, possible but I don't like the idea too much.

**Comment by dceejay** [comment]
> I think the solution lies in the dashboard not sending messages back which originates from the ui-node itself and not storing this for replay.

Yes that is what the PR did - It turned off the returning message being stored. Which then should mean it doesn't get resent.

**Comment by MichaelLeeHobbs** [comment]
> well a heads up on the additional issue would be appreciated so we could fix it.
> (as we have with the one above)

I suspect the unreported issues will go away once this fix is live. I will retest later and report them if they are still around.

**Comment by dceejay** [comment]
it's live now - as 0.3.0

**Comment by MichaelLeeHobbs** [comment]
I will take a look this weekend and see if all issues are resolved! Thanks.
