### ISSUE TITLE
ui-table does not work (Debian Buster)

### ISSUE THREAD

**Issue by TotallyInformation** [node-red/node-red-ui-nodes#30]
### Which node are you reporting an issue on?

node-red-ui-table

### What are the steps to reproduce?

See below.

### What happens?

No data is shown in the ui and the ui-tab containing the table is not shown correctly.

### Please tell us about your environment:

- [x] Node-RED version: v1.0.3
- [x] node.js version: v12.16.1
- [x] npm version: 6.13.4
- [x] Platform/OS: Lenovo laptop running Debian Buster
- [x] Browser: Any. Main tests done using Microsoft Edge Dev.

## Details

![image](https://user-images.githubusercontent.com/1591850/75363204-b194dc00-58b1-11ea-860b-139f8b30b042.png)

```
Welcome to Node-RED
===================
26 Feb 16:00:03 - [info] Node-RED version: v1.0.3
26 Feb 16:00:03 - [info] Node.js  version: v12.16.1
26 Feb 16:00:03 - [info] Linux 4.19.0-8-amd64 x64 LE
26 Feb 16:00:03 - [info] Loading palette nodes
26 Feb 16:00:03 - [info] Settings file  : /home/home/nrmain/data/settings.js
26 Feb 16:00:04 - [info] HTTP Static    : /home/home/nrmain/public
26 Feb 16:00:04 - [info] Context store  : 'default' [module=memory]
26 Feb 16:00:04 - [info] Context store  : 'file' [module=localfilesystem]
26 Feb 16:00:04 - [info] User directory : /home/home/nrmain/data
26 Feb 16:00:04 - [warn] Projects disabled : editorTheme.projects.enabled=false
26 Feb 16:00:04 - [info] Flows file     : /home/home/nrmain/data/nrmain_flows.json
26 Feb 16:00:04 - [info] Server now running at http://127.0.0.1:1880/red/
26 Feb 16:00:04 - [info] Starting flows
26 Feb 16:00:04 - [info] Started flows
26 Feb 16:00:45 - [info] Installing module: node-red-dashboard, version: 2.19.4
26 Feb 16:00:47 - [info] Installed module: node-red-dashboard
26 Feb 16:00:47 - [info] Dashboard version 2.19.4 started at /ui
```
ui-table installed:
```
26 Feb 16:04:52 - [info] Installing module: node-red-node-ui-table, version: 0.2.2
26 Feb 16:04:53 - [info] Installed module: node-red-node-ui-table
26 Feb 16:04:53 - [info] Added node types:
26 Feb 16:04:53 - [info]  - node-red-node-ui-table:ui_table
```
Imported the simple example, changed the tabname to home2:
![image](https://user-images.githubusercontent.com/1591850/75363884-ae4e2000-58b2-11ea-9866-cac7addb072e.png)

 and deployed:
```
26 Feb 16:08:13 - [info] Stopping modified nodes
26 Feb 16:08:13 - [info] Stopped modified nodes
26 Feb 16:08:13 - [info] Starting modified nodes
Error: Cannot find module 'node-red-dashboard'
    at Object.requireModule [as require] (/home/home/nrmain/node_modules/@node-red/registry/lib/util.js:48:19)
    at new TableNode (/home/home/nrmain/data/node_modules/node-red-node-ui-table/node.js:48:30)
    at Object.createNode (/home/home/nrmain/node_modules/@node-red/runtime/lib/nodes/flows/util.js:483:31)
    at Flow.start (/home/home/nrmain/node_modules/@node-red/runtime/lib/nodes/flows/Flow.js:189:48)
    at start (/home/home/nrmain/node_modules/@node-red/runtime/lib/nodes/flows/index.js:329:33)
    at /home/home/nrmain/node_modules/@node-red/runtime/lib/nodes/flows/index.js:196:21 {
  code: 'MODULE_NOT_FOUND'
}
26 Feb 16:08:13 - [info] Started modified nodes
```

Result is that no second ui tab is shown. Manually move the table card to the main ui tab and redeploy. The table still isn't shown even after reloading the page and re-injecting the data.

![image](https://user-images.githubusercontent.com/1591850/75364081-06852200-58b3-11ea-87ac-1076c43d76c7.png)

----

Delete the flow and the tabs/cards except a single "Home" ui tab. Redeploy. Then add example #2 flow and deploy:

![image](https://user-images.githubusercontent.com/1591850/75364349-801d1000-58b3-11ea-9db1-e497546324a1.png)

Now NOTHING shows in the dashboard other than the default welcome to the dashboard.
![image](https://user-images.githubusercontent.com/1591850/75364448-ac389100-58b3-11ea-8680-38cd821abd0e.png)

----

Go back to start. Reset everything, reinstall Dashboard. Add nodes 2 two different ui tabs and confirm everything works. Reinstall ui-table. Add manually to flow and set to use a new, manually created ui tab and use same data input as in the simple example. On deployment, I get the same cannot find module error and the new ui tab never appears.

**Comment by dceejay** [comment]
(as usual)... working fine here....
The line it is complaining about is 
```
RED.require('node-red-dashboard')(RED);
```
Wondering if it's anything to do with the way you load node-red locally ?

**Comment by Christian-Me** [comment]
I gave it a try on a virtual box ubuntu 18.04.1 LTE - unfortunate I can reproduce the problem:
Fresh install of 
- node.js, 8.10.0
- npm 0.34.0
- node-red V1.0.3
- dashboard version 2.19.4
- ui-table version 0.2.2.

On my windows machines running 0.2.1 of ui-table all works fine.
Perhaps something happened between 0.2.2 and 0.2.1?

```
27 Feb 09:10:19 - [info] Starting flows
{ Error: Cannot find module 'node-red-dashboard'
    at Object.requireModule [as require] (/usr/local/lib/node_modules/node-red/node_modules/@node-red/registry/lib/util.js:48:19)
    at new TableNode (/home/cmeinert/.node-red/node_modules/node-red-node-ui-table/node.js:48:30)
    at Object.createNode (/usr/local/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/flows/util.js:483:31)
    at Flow.start (/usr/local/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/flows/Flow.js:189:48)
    at start (/usr/local/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/flows/index.js:329:33)
    at stop.then.then (/usr/local/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/flows/index.js:196:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) code: 'MODULE_NOT_FOUND' }

```

**Comment by Christian-Me** [comment]
I was too fast, sorry just recognized that nodejs is quite old ... I do not use this machine very often ;)
updated nodejs to 13.9.0 ...

```
27 Feb 09:27:45 - [info] Node-RED Version: v1.0.3
27 Feb 09:27:45 - [info] Node.js  Version: v13.9.0
27 Feb 09:27:45 - [info] Linux 5.3.0-40-generic x64 LE
```

and here we go:
![image](https://user-images.githubusercontent.com/15779507/75425847-c9b53b80-5943-11ea-8fa9-a8ac25e68446.png)

**Comment by dceejay** [comment]
so all ok for you ?

**Comment by Christian-Me** [comment]
Sorry not to be clear. Yes after upgrade to node.js 13.9.0 the ui-table example works fine!

All ok for now.

**Comment by dceejay** [comment]
(though we don't support node 13...  preferring LTS versions.... but hmm - Julian already on 12. (as was I).

**Comment by Christian-Me** [comment]
Sorry when it comes to linux I feel like a monkey: barely able to type or read understanding nearly nothing. So the only way I do is google, copy, paste, hope ....

I accident grabbed the current version instead of the LTS, ups.

**Comment by TotallyInformation** [comment]
I'm prepared to concede that this is down to the way I install Node-RED. However, that method is perfectly valid and everything else works just fine. All I'm doing is installing NR locally to a folder and running it from there with the userDir folder directly beneath it. So I can't see why the require would fail.

**Comment by TotallyInformation** [comment]
On Windows 10 with same configuration:

I get the following warning:
```
1|Node-RED  | 27 Feb 18:12:35 - [info] Stopped modified nodes
1|Node-RED  | 27 Feb 18:12:35 - [info] Starting modified nodes
1|Node-RED  | 27 Feb 18:12:35 - [warn] [ui_table:5a802dcb.0e64a4] *** Order property not set. Please contact developer. ***
1|Node-RED  | 27 Feb 18:12:35 - [info] Started modified nodes
```

But everything works as expected.

Actually slight difference on Windows - the version of Node.js installed is v12.14.0, npm is the same though (v6.13.4). Otherwise same versions of the nodes and of Node-RED, same browser.

**Comment by TotallyInformation** [comment]
Well that stinks. I update node.js to the latest LTS on my W10 device and now I get this:

```
1|Node-RED  | Welcome to Node-RED
1|Node-RED  | ===================
1|Node-RED  | 27 Feb 19:34:45 - [info] Node-RED version: v1.0.3
1|Node-RED  | 27 Feb 19:34:45 - [info] Node.js  version: v12.16.1
1|Node-RED  | 27 Feb 19:34:45 - [info] Windows_NT 10.0.18363 x64 LE
1|Node-RED  | 27 Feb 19:34:48 - [info] Loading palette nodes
1|Node-RED  | Thu, 27 Feb 2020 19:34:52 GMT node-telegram-bot-api deprecated Automatic enabling of cancellation of promises is deprecated.
1|Node-RED  | In the future, you will have to enable it yourself.
1|Node-RED  | See https://github.com/yagop/node-telegram-bot-api/issues/319. at internal\modules\cjs\loader.js:1158:30
1|Node-RED  | 27 Feb 19:34:53 - [info] +-----------------------------------------------------
1|Node-RED  | 27 Feb 19:34:53 - [info] | uibuilder initialised:
1|Node-RED  | 27 Feb 19:34:53 - [info] |   root folder: C:\src\nr2\data\uibuilder
1|Node-RED  | 27 Feb 19:34:53 - [info] |   version . .: 3.0.0-dev1
1|Node-RED  | 27 Feb 19:34:53 - [info] |   packages . : vue,bootstrap,bootstrap-vue,jquery,moonjs,socket.io
1|Node-RED  | 27 Feb 19:34:53 - [info] +-----------------------------------------------------
1|Node-RED  | [NRTEST:module] RED.settings.contextStorage { default: { module: 'memory' }, file: { module: 'localfilesystem' } }
1|Node-RED  | 27 Feb 19:34:53 - [info] Dashboard version 2.19.3 started at /nr/ui
1|Node-RED  | 27 Feb 19:34:54 - [info] Settings file  : C:\src\nr2\data\settings.js
1|Node-RED  | 27 Feb 19:34:54 - [info] HTTP Static    : C:\src\nr2\public
1|Node-RED  | 27 Feb 19:34:54 - [info] Context store  : 'default' [module=memory]
1|Node-RED  | 27 Feb 19:34:54 - [info] Context store  : 'file' [module=localfilesystem]
1|Node-RED  | 27 Feb 19:34:54 - [info] User directory : C:\src\nr2\data
1|Node-RED  | 27 Feb 19:34:54 - [warn] No active project : using default flows file
1|Node-RED  | 27 Feb 19:34:54 - [info] Flows file     : C:\src\nr2\data\flows_DESKTOP-M1M6R28.json
1|Node-RED  | 27 Feb 19:34:54 - [info] Server now running at http://127.0.0.1:1880/red/
1|Node-RED  | 27 Feb 19:34:54 - [warn] Error loading credentials: SyntaxError: Unexpected token 
                                                                                                 in JSON at position 0
1|Node-RED  | 27 Feb 19:34:54 - [warn] Error loading flows: Error: Failed to decrypt credentials
```

The credentials file is certainly valid JSON and the timestamp on the file is from December:
![image](https://user-images.githubusercontent.com/1591850/75480168-aec0e680-5998-11ea-85c4-12a017250bd5.png)

**Comment by dceejay** [comment]
so ok to close now ?

**Comment by TotallyInformation** [comment]
Well only if you don't mind it still not working on Debian Buster. No difference there.

**Comment by dceejay** [comment]
It's working fine on Buster here . Ok - so the bit above where you say it's now working is on Windows ? and the projects piece was just a distraction...

**Comment by TotallyInformation** [comment]
It always worked on Windows. I just updated Node.js to the same version that I have on Buster just to make sure there is no problem there. There isn't.

The projects part was just me sounding off my frustration since the Node.js installation for some reason hosed my projects. A distraction, sorry.

On my Buster install which uses exactly the same installation format as Windows and indeed as my 2 Pi's and which has been working fine for a couple of years now, ui-table fails as indicated. It does not appear to be able to find the dashboard module for some reason.

**Comment by TotallyInformation** [comment]
OK, this is weird. Following on from some further chatter on ui table and context menu in the forum, I decided that I would try this again to see if I could spot the problem.

This time though, everything is working!

So I can no longer do any debugging on this. Sorry. I guess we will have to close this for now until someone else stumbles upon the same set of circumstances?
