### ISSUE TITLE
Not possible to set functionality movableColumns via ui_control

### ISSUE THREAD

**Issue by aiot-maker** [node-red/node-red-ui-nodes#34]
### Which node are you reporting an issue on?
node-red-node-ui-table

### What are the steps to reproduce?

In a change node set property below to false
ui_control.tabulator.movableColumns
feed the output of the change node to the ui_table node

### What happens?
On the dashboard it is still possible to move table columns (drag and dropping)

### What do you expect to happen?
I was expecting to disable the moveColumns functionality 

I could trace to problem to this line code:

`if (!ui_control.tabulator.movableColumns) opts.movableColumns = true;`

Apparently its purpose is to setup a default `true` in case the property is not defined by the user with ui_control

Changing the code to below fix the issue. It will set a default but afterwards it is possible to change it with the ui_control

`if (!ui_control.tabulator.hasOwnProperty("movableColumns")) opts.movableColumns = true;`

### Please tell us about your environment:

- [ ] Node-RED version: v1.1.1
- [ ] node.js version: v12.16.3
- [ ] npm version:
- [ ] Platform/OS: Windows 10
- [ ] Browser: Chrome
- [] Dashboard: 2.22.1

**Comment by dceejay** [comment]
yes - good spot

**Comment by dceejay** [comment]
This should now be fixed by the v0.3.2

**Comment by aiot-maker** [comment]
Working perfectly now. Thank you very much indeed.
