### ISSUE TITLE
UI-Table nested column headers broken

### ISSUE THREAD

**Issue by Gonzo4** [node-red/node-red-ui-nodes#37]
### Which node are you reporting an issue on?
UI-Table
### What are the steps to reproduce?
Load [example 3](https://github.com/node-red/node-red-ui-nodes/blob/master/node-red-node-ui-table/examples/3%20ui_control%20table.json) with ui-table version 0.3.4 and deploy.
### What happens?
Nested table headers broken, see images...

With version 0.3.1
![grafik](https://user-images.githubusercontent.com/6013729/90962357-a8c34280-e4af-11ea-81f3-23d24b639f16.png)

With version 0.3.4
![grafik](https://user-images.githubusercontent.com/6013729/90962440-4b7bc100-e4b0-11ea-94b1-e8b3e6024120.png)

### What do you expect to happen?
Same as with version 0.3.1
### Please tell us about your environment:

- [ ] Node-RED version: 1.0.6
- [ ] node.js version: 10.17.0
- [ ] npm version: 6.11.3
- [ ] Platform/OS: Win 10
- [ ] Browser: Firefox

**Comment by Christian-Me** [comment]
Thank you for spotting that bug. Didn't noticed your issue, sorry. But Your issue should be fixed with the latest pr.

**Comment by Gonzo4** [comment]
Thanks, now it works ;)
