### ISSUE TITLE
UI-Table nested column headers appended if set multiple times over ui_control

### ISSUE THREAD

**Issue by Gonzo4** [node-red/node-red-ui-nodes#40]
@Christian-Me Sorry, next bug found :innocent:

### Which node are you reporting an issue on?
UI-Table

### What are the steps to reproduce?
Load [example 3](https://github.com/node-red/node-red-ui-nodes/blob/master/node-red-node-ui-table/examples/3%20ui_control%20table.json) with ui-table version 0.3.5 and press the inject button multiple times.

### What happens?
Nested columns are appended on each ui_control message.

![grafik](https://user-images.githubusercontent.com/6013729/92993673-ac1c7d80-f4f3-11ea-9114-54701f6f98e5.png)

### What do you expect to happen?
Same as with version 0.3.1

### Please tell us about your environment:

- [ ] Node-RED version: 1.0.6
- [ ] node.js version: 10.17.0
- [ ] npm version: 6.11.3
- [ ] Platform/OS: Win 10
- [ ] Browser: Firefox

**Comment by Christian-Me** [comment]
It is actually the same as before (merging configurations) not really solved.
Grouped column parents has to be identified by title instead of field to find matches during merge.
So the first wasn't solved. Will look into it as soon as I can. Sorry.

**Comment by Gonzo4** [comment]
No problem, the 3.1.0 still works :relaxed:

**Comment by Gonzo4** [comment]
@Christian-Me It works, many thanks 👍  => I think this issue could be closed
