### ISSUE TITLE
Does not work with Google chrome?  Example flow displays blank dashboard panel named "List" on in Chrome?

### ISSUE THREAD

**Issue by Nodi-Rubrum** [node-red/node-red-ui-nodes#42]
On Raspberry Pi OS 10 Buster
- Node Red 1.1.0
- Dashboard 2.23

Browser And OS...
- Windows 10 Pro 64-bit
- Chrome Version 85.0.4183.121 (Official Build) (64-bit)

For Example...
![image](https://user-images.githubusercontent.com/69404967/94814229-e8822180-03ad-11eb-97e5-f5b519af370c.png)

Did additional testing... DOES NOT DISPLAY CORRECTLY in Microsoft Edge, FireFox, etc.

**Comment by knolleary** [comment]
Hi, please use the issue template we provide.

In this instance, it isn't clear what node you are reporting this issue against. The repository contains 6 different nodes.

**Comment by dceejay** [comment]
and there is no example flow...
