### ISSUE TITLE
Why does selection of current item, NOT create 'selected' value?

### ISSUE THREAD

**Issue by Nodi-Rubrum** [node-red/node-red-ui-nodes#43]
Why does selection of current (initial) item, does not create 'selected' value?  Say a list of 5 items, 0,1,2,3,4.  If 0 is the initial current item, then selecting 0 again., the selected value is not established.  This makes no sense.  If 1,2,3,4 are selected, then the 'selected' value in the payload IS established.  Sorry but don't understand this design logic.  Seems like a bug.  If any item is selected then the 'selected' value should be established, this logic makes more sense to me.

**Comment by Nodi-Rubrum** [comment]
Here is a flow that reproduces the issue I am seeing, where if first item in list is selected, the selected part of payload is not created, but any other item in the drop down menu list the selected part is created.

`[{"id":"4e4f8e04.286e4","type":"ui_list","z":"f2098add.395fe8","group":"50bb25ba.66c3dc","name":"List","order":1,"width":6,"height":7,"lineType":"two","actionType":"menu","allowHTML":false,"outputs":1,"topic":"","x":630,"y":260,"wires":[["5a75c710.586698","8a211eb7.57f9e","a9a38426.6fc3d8"]]},{"id":"760ee89c.7ccbe8","type":"function","z":"f2098add.395fe8","name":"Generate","func":"const PERSISTENT = 'persistent';\n\nvar theZones = flow.get('Zones', PERSISTENT),\n    theZone = flow.get('Zone', PERSISTENT);\n\nmsg.payload=[\n                { \n                    \"menu\": Array.from(Array(theZones).keys()),\n                    \"title\": `Zone ${theZone}`\n                }\n            ];\n\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","x":480,"y":260,"wires":[["4e4f8e04.286e4"]]},{"id":"768586b.cb88578","type":"inject","z":"f2098add.395fe8","name":"Automatic","props":[{"p":"payload"}],"repeat":"","crontab":"","once":true,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":170,"y":280,"wires":[["c59b2083.012de"]]},{"id":"c59b2083.012de","type":"change","z":"f2098add.395fe8","name":"Set","rules":[{"t":"set","p":"#:(persistent)::Zones","pt":"flow","to":"5","tot":"num"},{"t":"set","p":"#:(persistent)::Zone","pt":"flow","to":"0","tot":"num"}],"action":"","property":"","from":"","to":"","reg":false,"x":330,"y":280,"wires":[["760ee89c.7ccbe8"]]},{"id":"5a75c710.586698","type":"debug","z":"f2098add.395fe8","name":"Message","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":840,"y":360,"wires":[]},{"id":"7401550f.643a4c","type":"link in","z":"f2098add.395fe8","name":"","links":["8a211eb7.57f9e"],"x":365,"y":240,"wires":[["760ee89c.7ccbe8"]]},{"id":"8a211eb7.57f9e","type":"link out","z":"f2098add.395fe8","name":"","links":["7401550f.643a4c"],"x":735,"y":200,"wires":[]},{"id":"a9a38426.6fc3d8","type":"change","z":"f2098add.395fe8","name":"Set","rules":[{"t":"set","p":"#:(persistent)::Zone","pt":"flow","to":"payload.selected","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":770,"y":260,"wires":[[]]},{"id":"50bb25ba.66c3dc","type":"ui_group","z":"","name":"List","tab":"85b8321a.ad37d","order":1,"disp":true,"width":"6","collapse":false},{"id":"85b8321a.ad37d","type":"ui_tab","z":"","name":"Test","icon":"dashboard","order":2,"disabled":false,"hidden":false}]`

**Comment by Nodi-Rubrum** [comment]
This was an interesting scenario.  Below is a flow that always returns the menu item selected, even if the selected item is the first item in the list, and selected twice in a row.

`[{"id":"4e4f8e04.286e4","type":"ui_list","z":"f2098add.395fe8","group":"50bb25ba.66c3dc","name":"List","order":1,"width":6,"height":7,"lineType":"two","actionType":"menu","allowHTML":false,"outputs":1,"topic":"","x":630,"y":280,"wires":[["2176ba65.0c7006"]]},{"id":"760ee89c.7ccbe8","type":"function","z":"f2098add.395fe8","name":"Generate","func":"const PERSISTENT = 'persistent';\n\nvar theZones = flow.get('Zones', PERSISTENT),\n    theZone = flow.get('Zone', PERSISTENT);\n\nmsg.payload=[\n                { \n                    \"menu\": Array.from(Array(theZones).keys()),\n                    \"title\": `Zone ${theZone}`\n                }\n            ];\n\nvar theMessage = {\n    'zone': theZone\n}\n\nreturn [msg, theMessage];","outputs":2,"noerr":0,"initialize":"","finalize":"","x":480,"y":300,"wires":[["4e4f8e04.286e4"],["976ebd8.90cd54"]]},{"id":"768586b.cb88578","type":"inject","z":"f2098add.395fe8","name":"Automatic","props":[{"p":"payload"}],"repeat":"","crontab":"","once":true,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":170,"y":300,"wires":[["c59b2083.012de"]]},{"id":"c59b2083.012de","type":"change","z":"f2098add.395fe8","name":"Set","rules":[{"t":"set","p":"#:(persistent)::Zones","pt":"flow","to":"5","tot":"num"},{"t":"set","p":"#:(persistent)::Zone","pt":"flow","to":"0","tot":"num"}],"action":"","property":"","from":"","to":"","reg":false,"x":330,"y":280,"wires":[["760ee89c.7ccbe8"]]},{"id":"7401550f.643a4c","type":"link in","z":"f2098add.395fe8","name":"","links":["527d166b.c42668","8a211eb7.57f9e"],"x":355,"y":320,"wires":[["760ee89c.7ccbe8"]]},{"id":"8a211eb7.57f9e","type":"link out","z":"f2098add.395fe8","name":"","links":["f3e4caa2.0a4098","7401550f.643a4c"],"x":1035,"y":300,"wires":[]},{"id":"a9a38426.6fc3d8","type":"change","z":"f2098add.395fe8","name":"Set","rules":[{"t":"set","p":"#:(persistent)::Zone","pt":"flow","to":"payload.selected","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":930,"y":300,"wires":[["8a211eb7.57f9e"]]},{"id":"2176ba65.0c7006","type":"switch","z":"f2098add.395fe8","name":"Select?","property":"payload.selected","propertyType":"msg","rules":[{"t":"istype","v":"undefined","vt":"undefined"},{"t":"else"}],"checkall":"true","repair":false,"outputs":2,"x":780,"y":280,"wires":[["6292c622.0a3b48"],["a9a38426.6fc3d8"]]},{"id":"6292c622.0a3b48","type":"link out","z":"f2098add.395fe8","name":"","links":["55fefaf5.4bd204"],"x":895,"y":260,"wires":[]},{"id":"55fefaf5.4bd204","type":"link in","z":"f2098add.395fe8","name":"","links":["6292c622.0a3b48"],"x":215,"y":260,"wires":[["c59b2083.012de"]]},{"id":"976ebd8.90cd54","type":"debug","z":"f2098add.395fe8","name":"Message","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":640,"y":320,"wires":[]},{"id":"50bb25ba.66c3dc","type":"ui_group","z":"","name":"List","tab":"85b8321a.ad37d","order":1,"disp":true,"width":"6","collapse":false},{"id":"85b8321a.ad37d","type":"ui_tab","z":"","name":"Test","icon":"dashboard","order":2,"disabled":false,"hidden":false}]`

**Comment by knolleary** [comment]
Please use the issue template. You don't identify the node you are asking about. If you have general questions, please use the forum.

**Comment by Nodi-Rubrum** [comment]
Node was identified in the flow.
