### ISSUE TITLE
Can not install for npm

### ISSUE THREAD

**Issue by Shadow-Ding** [node-red/node-red-ui-nodes#5]
I have tried to install lineargauge node and table node by using`npm i node-red-ui-node-lineargauge` and `npm install node-red-ui-node-table`.
They both failed and the error shows they are not in the  npm registry.
Is there something wrong ?

**Comment by knolleary** [comment]
Nothing is wrong... we just haven't got to the point of publishing them to npm yet.

If you are desperate to try them, you could use `npm install node-red-ui-nodes/node-red-ui-node-table` to install from the git repo instead.

**Comment by Shadow-Ding** [comment]
Thanks a lot, knolleary. That's exactly what I want.
