### ISSUE TITLE
ui_table node - Order property not set

### ISSUE THREAD

**Issue by Paul-Reed** [node-red/node-red-ui-nodes#80]
### Which node are you reporting an issue on?
node-red-node-ui-table
### What are the steps to reproduce?
Open any ui_table example flow 
### What happens?
Get a warning in debug panel - `"*** Order property not set. Please contact developer. ***"`
### What do you expect to happen?
Not to get the warning!
### Please tell us about your environment:

- [ ] Node-RED version: 2.1.6
- [ ] node.js version: 14.18.3
- [ ] npm version: 6.14.15
- [ ] Platform/OS: Raspbian Buster
- [ ] Browser: Windows Chrome v97.0.4692.99 (Official Build) (64-bit)

**Comment by dceejay** [comment]
Which version of ui-table node do you have installed ? And which version of dashboard ?
When exactly do you get that message ? When you paste the example ? when you deploy ? After a restart/refresh ?

**Comment by Paul-Reed** [comment]
> Which version of ui-table node do you have installed ?

The current version - v0.3.11

> And which version of dashboard ?

The current version - v3.1.5

> When exactly do you get that message ? When you paste the example ? when you deploy ? After a restart/refresh ?

![table](https://user-images.githubusercontent.com/973580/151673817-03067a64-21d2-422d-850d-0e305f305325.gif)
