### ISSUE TITLE
ui-table style of html links changed with v0.4.0

### ISSUE THREAD

**Issue by m-schaeffler** [node-red/node-red-ui-nodes#86]
### Which node are you reporting an issue on?
node-red-node-ui-table

### What are the steps to reproduce?
use HTML links in a table

### What happens?
with v.0.3.12 the links were white on dark gray
with v0.4.0 they are blue on dark gray

### What do you expect to happen?
the links should stay in white on gray, because a change should not break the appearance of the dashboard.

### Please tell us about your environment:

- [ ] Node-RED version: 3.0.2
- [ ] node.js version: 16.17.0-deb-1nodesource1
- [ ] npm version:
- [ ] Platform/OS: Raspian 11.4
- [ ] Browser: Firefox

**Comment by m-schaeffler** [comment]
sorry, but isue is not vfixed with v4.0.1

**Comment by dceejay** [comment]
I have reverted (republished) the older 0.3.x as 0.4.2  (complete with old vulnerabilities) and moved the latest library version to a new branch while we work on it to make it more compatible.
