### ISSUE TITLE
ui-tables: alignment no longer working with v0.4.0

### ISSUE THREAD

**Issue by m-schaeffler** [node-red/node-red-ui-nodes#87]
### Which node are you reporting an issue on?
node-red-node-ui-table v0.4.0

### What are the steps to reproduce?
set alignment of one column to center or right

### What happens?
instead of center or right the column is left aligned

### What do you expect to happen?
alignment setting is respected

### Please tell us about your environment:

- [ ] Node-RED version: 3.0.2
- [ ] node.js version: 16.17.0-deb-1nodesource1
- [ ] npm version:
- [ ] Platform/OS: Raspian 11.4
- [ ] Browser: Firefox

**Comment by suttridge** [comment]
No, I'm afraid v0.4.1 does not fix this - it is still the same - every column is left-aligned no matter what the setting is.

**Comment by m-schaeffler** [comment]
sorry, but the issue is not fixed with 4.0.1

**Comment by m-schaeffler** [comment]
alignement is working, if you reselect the used alignement in the properties.

**Comment by suttridge** [comment]
Ah yes, have to go and change each alignment selector in every table, and then it is fine.  Thanks.

**Comment by dceejay** [comment]
I have reverted (republished) the older 0.3.x as 0.4.2  (complete with old vulnerabilities) and moved the latest library version to a new branch while we work on it to make it more compatible.
